### ISSUE TITLE
More robust error handling.

### ISSUE THREAD

**Issue by BenTheElder** [BenTheElder/slack-rs#12]
Api calls need to more thoroughly check for slack api errors and ensure the return data matches expectations as noted in the slack api docs. We need to handle fields like `err` and `ok` as well as expected values throughout the api and return an `Error::Api` when they fail.

Also, the description strings need to be reviewed for consistency throughout.

**Comment by BenTheElder** [comment]
#17 as well as some other prior commits should close this.

**Comment by mthjones** [comment]
There is the possibility of making an enum for the different Slack API error types (i.e. like at [the bottom here](https://api.slack.com/methods/channels.create)). Would help clients handle errors better so they don't have to parse the internal string.

That could be captured in another issue though, since I believe the case that this covered has been resolved now.

**Comment by BenTheElder** [comment]
I agree that this would make another good issue, we've covered actually
handling errors pretty well, parsing slack errors and typing those in rust
would be a good improvement, maybe Error::Api could become an enum over the
sets of slack errors.

**Comment by BenTheElder** [comment]
Closing and opening a new issue for typed Slack API errors.
