### ISSUE TITLE
Parse Rtm Events

### ISSUE THREAD

**Issue by BenTheElder** [BenTheElder/slack-rs#23]
Implement parsing for https://api.slack.com/rtm events similar to how [Message](https://api.slack.com/events/message) events are currently handled.

Also: change the RTM client api `on_receive` to instead be `on_event` with an `Event` enum instead of the raw json.

**Comment by BenTheElder** [comment]
cc @mthjones, thoughts? I'm currently working on writing the enum for `Event`.

**Comment by mthjones** [comment]
Sounds like a good idea! I think the implementation should be very similar to how `MessageEvent` was done. For decoding, just switch on the `type` field instead of `subtype` (and pass off to `MessageEvent` when it's of type `message`).

If I can make one recommendation, since this is going to be breaking anyways: the name of the current `MessageEvent` should change to `Message` and make `MessageEvent` the enum type in the RTM event instead (i.e. `MessageEvent(Message)`).

Having the method be `on_event` will be _so_ much nicer for working with incoming messages. As a point of example, from my `slackbot` crate (which needs a bit of love now), [here's what I think it might look like after the change](https://gist.github.com/mthjones/9daa85eb68d7eb3045ad). :+1:

**Comment by BenTheElder** [comment]
Yeah, that looks much nicer.
I started building it pretty much how you said earlier (switched to
studying for a quiz now, back to it later this week at some point).
I like the suggestion to change the MessageEvent name, I was going to look
into nesting Message within Event, but that doesn't seem to be possible (?)

**Comment by BenTheElder** [comment]
This is done (locally) but I still have to write the tests.

**Comment by BenTheElder** [comment]
Work is on the new [`devel`](https://github.com/BenTheElder/slack-rs/tree/devel) branch, I basically just pushed what I had as I've gotten a bit busy again, it still needs more testing and tests.

**Comment by mthjones** [comment]
Sorry, I've been tied up with lots of work recently and haven't had a chance to do much here. I looked through the `devel` branch and it looks good! If you want, I'd be happy to do an actual review if it goes up in a PR. :)

**Comment by BenTheElder** [comment]
I'd appreciate that, I'm working on actually using the library right now
(locally linked against devel), but I do plan to put up a PR to release
0.12.0 with the changes, probably within the next week.

I'm in the same boat but decided to take some time to work on it anyhow,
lots to do for classes.

**Comment by BenTheElder** [comment]
This is done, we could use tons more tests but i'm less focused on slack at the moment and will patch any parsing issues found, as is I'm more concerned by https://github.com/BenTheElder/slack-rs/issues/26, we may need to overhaul the parsing anyhow.
