### ISSUE TITLE
Using json::decode::<MessageEvent>(json_str) adds 60 seconds to release build time

### ISSUE THREAD

**Issue by dten** [BenTheElder/slack-rs#26]
I was trying to figure out why my --release build (incremental not fresh) took so long and i narrowed it down to usage of `json::decode::<MessageEvent>(json_str)` in on_receive

Is this expected? Is there anything I can do to avoid it? My alternative is manually parsing the messages i'm interested in. I guess it's just a `rustc` being slow at some stuff thing.

**Comment by BenTheElder** [comment]
I certainly do not expect that!
However, I'm no rust expert, so it's possible the way it's written is hard
on the compiler (?)
I'm buried in classwork right now but if you could post some more details
about your setup (rust version etc) I'll try to profile it myself when I
get time again.

cc @mthjones

**Comment by dten** [comment]
I made a gist based on the example code
https://gist.github.com/dten/c1d9c6503d6aa1973b91

a clean release build takes 300 seconds (line in)
comment out the line and build release again is 5 seconds
uncomment the line and release build is 66 seconds

this is on my laptop and using rustc 1.6.0-nightly (b7845f93b 2015-11-15)

**Comment by BenTheElder** [comment]
Thanks.
I haven't been using nightly recently, perhaps it's a bug with the nightly?
I'll try to figure out what's going on when I get some free time,
eventually we'll switch to serde for parsing once custom derive is
available on stable.

**Comment by dten** [comment]
just tried the stable. similar results; 5 seconds to 53 seconds

**Comment by dten** [comment]
attached two traces from using rustc -Z time-passes

not really sure what they mean but these two parts used to be ~1 second and are now the below values

  time: 23.207; rss: 263MB	llvm module passes
  time: 26.173; rss: 261MB	codegen passes

[slow.txt](https://github.com/BenTheElder/slack-rs/files/40952/slow.txt)
[fast.txt](https://github.com/BenTheElder/slack-rs/files/40953/fast.txt)

**Comment by mthjones** [comment]
That compile time...*woof*. I think it may be due to the number of variants that exist for the message event. I don't have my primary dev machine available right now, but I'll try and take a look at this.

**Comment by BenTheElder** [comment]
Getting to this today, sorry I've been pretty busy with end-of-the-semester work.
Looking at your traces first, no significant difference until the last three steps:
`fast`:
```
time: 2.562; rss: 155MB	LLVM passes
  time: 0.914; rss: 155MB	running linker
time: 0.916; rss: 155MB	linking
```
`slow`:
```
time: 49.809; rss: 180MB	LLVM passes
  time: 1.087; rss: 180MB	running linker
time: 1.089; rss: 180MB	linking
```

Looking at the `-Z time-llvm-passes` info, the `Machine Common Subexpression Elimination` and `Function Integration/Inlining` passes jump out as taking over 8 seconds each on the `slow` version!

Yikes! looks like we're stressing out the LLVM passes pretty bad.
Like @mthjones said, it's probably the number of variants in the return type stressing out the codegen pretty badly for some reason. I'm not really sure what the best route to solve that is. We could break up the type into more event subtypes but the enum would still have as many total variants in order to handle each type.... I'm not convinced that would actually help.

**Comment by BenTheElder** [comment]
In the next release, you won't need to call this yourself, while I'd like to try to fix this, I think the best thing to do will be to eventually move to serde for json parsing.
Until then incremental builds should improve a lot as the parsing will be done inside the `run` code in the slack crate (and not in your code, unless you really wanted to for some reason).
